**Simple Linear Regression**

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm

In [2]:
# Importing the dataset
dataset = pd.read_csv('C:/MAFAS/APU/CT046-3-M-AML/CT046 - LABS/Python LAB MATERIALS/Lab 6 - Linear Regression/kc_house_data.csv')
dataset.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503


In [3]:
dataset.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [4]:
x = dataset[dataset.columns[5]] # sqft_living
y = dataset[dataset.columns[2]] # price

In [5]:
X = sm.add_constant(x)
est = sm.OLS(y, X).fit()
print(est.summary())

                            OLS Regression Results                            
Dep. Variable:                  price   R-squared:                       0.493
Model:                            OLS   Adj. R-squared:                  0.493
Method:                 Least Squares   F-statistic:                 2.100e+04
Date:                Wed, 24 Sep 2025   Prob (F-statistic):               0.00
Time:                        16:11:12   Log-Likelihood:            -3.0027e+05
No. Observations:               21613   AIC:                         6.005e+05
Df Residuals:                   21611   BIC:                         6.006e+05
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -4.358e+04   4402.690     -9.899      

In [7]:
# Linear Regression
from sklearn.linear_model import LinearRegression
slr = LinearRegression()

In [8]:
# predicting on X_test....This is a rare occasion to predict the TV using one IV
x_1 = dataset['sqft_living'].values.reshape(-1, 1)
y_1 = dataset['price'].values.reshape(-1, 1)

slr.fit(x_1, y_1)
y_pred = slr.predict(x_1)
y_pred.round(2)

array([[287555.07],
       [677621.83],
       [172499.4 ],
       ...,
       [242655.3 ],
       [405416.97],
       [242655.3 ]])

In [9]:
from sklearn.metrics import r2_score
print('R2 Score:', round(r2_score(y_1, y_pred), 2))

R2 Score: 0.49


In [10]:
from sklearn.metrics import mean_squared_error
print("Mean Squared Error: ", round(mean_squared_error(y_1, y_pred), 3)) 

Mean Squared Error:  68351286833.04


**Multiple Linear Regression**

In [12]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm

In [13]:
# Importing the dataset
data = pd.read_csv('C:/MAFAS/APU/CT046-3-M-AML/CT046 - LABS/Python LAB MATERIALS/Lab 6 - Linear Regression/50_Startups.csv')
data.head()

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,New York,192261.83
1,162597.70,151377.59,443898.53,California,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


In [14]:
data.shape

(50, 5)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [16]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [17]:
data.describe()

,R&D Spend,Administration,Marketing Spend,Profit
count,50.000000,50.000000,50.000000,50.000000
mean,73721.615600,121344.639600,211025.097800,112012.639200
std,45902.256482,28017.802755,122290.310726,40306.180338
min,0.000000,51283.140000,0.000000,14681.400000
25%,39936.370000,103730.875000,129300.132500,90138.902500
50%,73051.080000,122699.795000,212716.240000,107978.190000
75%,101602.800000,144842.180000,299469.085000,139765.977500
max,165349.200000,182645.560000,471784.100000,192261.830000


In [18]:
data['State'].describe()

count           50
unique           3
top       New York
freq            17
Name: State, dtype: object

In [25]:
# Drop State variable
data = data.drop(['State'], axis = 1)

In [26]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit'], dtype='object')

In [27]:
x = data.drop(['Profit'], axis = 1)
y = data['Profit']

In [29]:
# Multiple Linear Regression
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x, y)
round(mlr.score(x, y), 2) # Return the R^2 

0.95

In [30]:
print(mlr.coef_)
print(round(mlr.intercept_, 3))

[ 0.80571505 -0.02681597  0.02722806]
50122.193


In [31]:
X = sm.add_constant(x)
est = sm.OLS(y, X)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Wed, 24 Sep 2025   Prob (F-statistic):           4.53e-30
Time:                        19:52:37   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.012e+04   6572.353     

In [33]:
# Predictions
predictions = mlr.predict(x)
predictions[0:2].round(2)

array([192521.25, 189156.77])

**Build a Linear Regression predictive model**

In [34]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [35]:
# training a linear regression model on train
mlr.fit(x_train, y_train)

LinearRegression()

In [36]:
# R2 Score = Accuracy
# Train Accuracy
print('Train Accuracy = ', round(mlr.score(x_train, y_train) * 100, 2), '%')
# Test Accuracy....This is the one we consider when evaluating the model
print('Test Accuracy = ', round(mlr.score(x_test, y_test)* 100, 2), '%')

Train Accuracy =  95.36 %
Test Accuracy =  90.01 %


In [37]:
# predicting on x_test
y_pred = mlr.predict(x_test)
y_pred.round(2)

array([126703.03,  84894.75,  98893.42,  46501.71, 129128.4 ,  50992.69,
       109016.55, 100878.46,  97700.6 , 113106.15])

In [38]:
from sklearn.metrics import r2_score
round(r2_score(y_test, y_pred), 2)

0.9

In [39]:
pd.DataFrame({'Actual': y_test.round(2), 'Predicted': y_pred.round(2)})

,Actual,Predicted
13,134307.35,126703.03
39,81005.76,84894.75
30,99937.59,98893.42
45,64926.08,46501.71
17,125370.37,129128.40
48,35673.41,50992.69
26,105733.54,109016.55
25,107404.34,100878.46
32,97427.84,97700.60
19,122776.86,113106.15


In [40]:
# calculating MSE, RMSE, MAE
from sklearn.metrics import mean_squared_error, mean_absolute_error
print("Mean Squared Error: ", round(mean_squared_error(y_test, y_pred), 2))
print('Mean Absolute Error: ', round(mean_absolute_error(y_test, y_pred), 2))  
print('Root Mean Squared Error: ', np.sqrt(mean_squared_error(y_test, y_pred)).round(2))

Mean Squared Error:  80926321.22
Mean Absolute Error:  6979.15
Root Mean Squared Error:  8995.91
